import { useState } from 'react';
import { HiOutlineShieldCheck, HiOutlineCheckCircle } from 'react-icons/hi2';
import { visitorAPI, accessCodeAPI } from '../../services/api';
import toast from 'react-hot-toast';
import { AccessCode } from '../../types';

const VerifyCodePage = () => {
  const [code, setCode] = useState('');
  const [visitorName, setVisitorName] = useState('');
  const [validatedCode, setValidatedCode] = useState<AccessCode | null>(null);
  const [step, setStep] = useState<'input' | 'validated' | 'done'>('input');
  const [loading, setLoading] = useState(false);

  const handleValidate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await accessCodeAPI.validate(code.toUpperCase().trim());
      setValidatedCode(res.data.accessCode);
      setStep('validated');
      toast.success('Code is valid!');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Invalid code');
      setValidatedCode(null);
    } finally {
      setLoading(false);
    }
  };

  const handleEntry = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await visitorAPI.entry({ visitorName, code: code.toUpperCase().trim() });
      toast.success('Entry recorded!');
      setStep('done');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to record entry');
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setCode('');
    setVisitorName('');
    setValidatedCode(null);
    setStep('input');
  };

  return (
    <div className="max-w-md mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-black text-gray-900 dark:text-white tracking-tight">Verify Code</h1>
        <p className="text-gray-400 mt-1 text-sm">Scan QR or enter access code manually</p>
      </div>

      {step === 'input' && (
        <div className="card">
          <form onSubmit={handleValidate} className="space-y-5">
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">Access Code</label>
              <input
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase())}
                className="input-field text-center text-2xl font-mono tracking-[0.3em] uppercase font-bold"
                placeholder="ENTER CODE"
                maxLength={8}
                required
              />
            </div>
            <button
              type="submit"
              disabled={loading || code.length < 4}
              className="btn-primary w-full flex items-center justify-center gap-2 text-sm"
            >
              <HiOutlineShieldCheck className="w-4 h-4" />
              {loading ? 'Validating...' : 'Validate Code'}
            </button>
          </form>
        </div>
      )}

      {step === 'validated' && validatedCode && (
        <div className="card">
          <div className="text-center mb-6">
            <div className="w-14 h-14 mx-auto bg-emerald-50 dark:bg-emerald-900/20 rounded-2xl flex items-center justify-center mb-3">
              <HiOutlineCheckCircle className="w-7 h-7 text-emerald-600" />
            </div>
            <h3 className="text-base font-bold text-emerald-600">Code is Valid</h3>
          </div>

          <div className="space-y-0 mb-6 rounded-xl overflow-hidden border border-gray-100 dark:border-[#2a2a2a]">
            {[
              { label: 'Code', value: <span className="font-mono font-bold text-gray-900 dark:text-white tracking-widest">{validatedCode.code}</span> },
              { label: 'Type', value: <span className={validatedCode.type === 'GUEST' ? 'badge-active' : 'badge-pending'}>{validatedCode.type}</span> },
              {
                label: 'Generated By',
                value: <span className="text-gray-700 dark:text-gray-300 text-sm">
                  {typeof validatedCode.generatedBy === 'object'
                    ? `${validatedCode.generatedBy.name} (${validatedCode.generatedBy.flatNumber || 'N/A'})`
                    : 'N/A'}
                </span>
              },
              { label: 'Remaining Uses', value: <span className="font-semibold text-gray-900 dark:text-white">{validatedCode.usageLimit - validatedCode.usedCount}</span> },
            ].map((row, i, arr) => (
              <div
                key={row.label}
                className={`flex justify-between items-center px-4 py-3 ${i < arr.length - 1 ? 'border-b border-gray-100 dark:border-[#2a2a2a]' : ''}`}
              >
                <span className="text-xs text-gray-400 font-medium">{row.label}</span>
                {row.value}
              </div>
            ))}
          </div>

          <form onSubmit={handleEntry} className="space-y-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">Visitor Name</label>
              <input
                type="text"
                value={visitorName}
                onChange={(e) => setVisitorName(e.target.value)}
                className="input-field"
                placeholder="Enter visitor's name"
                required
              />
            </div>
            <div className="flex gap-3">
              <button type="button" onClick={reset} className="btn-secondary flex-1 text-sm py-2.5">Cancel</button>
              <button type="submit" disabled={loading} className="btn-success flex-1 text-sm py-2.5">
                {loading ? 'Recording...' : 'Record Entry'}
              </button>
            </div>
          </form>
        </div>
      )}

      {step === 'done' && (
        <div className="card text-center py-10">
          <div className="w-16 h-16 mx-auto bg-emerald-50 dark:bg-emerald-900/20 rounded-3xl flex items-center justify-center mb-5">
            <HiOutlineCheckCircle className="w-8 h-8 text-emerald-600" />
          </div>
          <h3 className="text-xl font-black text-gray-900 dark:text-white mb-2">Entry Recorded</h3>
          <p className="text-gray-400 text-sm mb-7">"{visitorName}" has been logged.</p>
          <button onClick={reset} className="btn-primary text-sm">Verify Another Code</button>
        </div>
      )}
    </div>
  );
};

export default VerifyCodePage;
