import { useState } from 'react';
import { HiOutlineShieldCheck, HiOutlineCheckCircle, HiOutlineXCircle } from 'react-icons/hi2';
import { visitorAPI, accessCodeAPI } from '../../services/api';
import toast from 'react-hot-toast';
import { AccessCode } from '../../types';

const VerifyCodePage = () => {
  const [code, setCode] = useState('');
  const [visitorName, setVisitorName] = useState('');
  const [validatedCode, setValidatedCode] = useState<AccessCode | null>(null);
  const [step, setStep] = useState<'input' | 'validated' | 'done'>('input');
  const [loading, setLoading] = useState(false);

  const handleValidate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await accessCodeAPI.validate(code.toUpperCase().trim());
      setValidatedCode(res.data.accessCode);
      setStep('validated');
      toast.success('Code is valid!');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Invalid code');
      setValidatedCode(null);
    } finally {
      setLoading(false);
    }
  };

  const handleEntry = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await visitorAPI.entry({ visitorName, code: code.toUpperCase().trim() });
      toast.success('Entry recorded!');
      setStep('done');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed to record entry');
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setCode('');
    setVisitorName('');
    setValidatedCode(null);
    setStep('input');
  };

  return (
    <div className="max-w-lg mx-auto">
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold">Verify Access Code</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">Scan QR or enter code manually</p>
      </div>

      {step === 'input' && (
        <div className="card">
          <form onSubmit={handleValidate} className="space-y-5">
            <div>
              <label className="block text-sm font-medium mb-2">Access Code</label>
              <input
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase())}
                className="input-field text-center text-2xl font-mono tracking-[0.3em] uppercase"
                placeholder="ENTER CODE"
                maxLength={8}
                required
              />
            </div>
            <button type="submit" disabled={loading || code.length < 4} className="btn-primary w-full py-3 text-base flex items-center justify-center gap-2">
              <HiOutlineShieldCheck className="w-5 h-5" />
              {loading ? 'Validating...' : 'Validate Code'}
            </button>
          </form>
        </div>
      )}

      {step === 'validated' && validatedCode && (
        <div className="card">
          <div className="text-center mb-6">
            <div className="w-16 h-16 mx-auto bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mb-3">
              <HiOutlineCheckCircle className="w-8 h-8 text-emerald-600" />
            </div>
            <h3 className="text-lg font-bold text-emerald-600">Code Valid</h3>
          </div>

          <div className="space-y-3 text-sm mb-6">
            <div className="flex justify-between py-2 border-b border-gray-100 dark:border-gray-800">
              <span className="text-gray-500">Code</span>
              <span className="font-mono font-bold">{validatedCode.code}</span>
            </div>
            <div className="flex justify-between py-2 border-b border-gray-100 dark:border-gray-800">
              <span className="text-gray-500">Type</span>
              <span className={validatedCode.type === 'GUEST' ? 'badge-active' : 'badge-pending'}>{validatedCode.type}</span>
            </div>
            <div className="flex justify-between py-2 border-b border-gray-100 dark:border-gray-800">
              <span className="text-gray-500">Generated By</span>
              <span className="font-medium">
                {typeof validatedCode.generatedBy === 'object'
                  ? `${validatedCode.generatedBy.name} (${validatedCode.generatedBy.flatNumber || 'N/A'})`
                  : 'N/A'}
              </span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-gray-500">Remaining Uses</span>
              <span className="font-medium">{validatedCode.usageLimit - validatedCode.usedCount}</span>
            </div>
          </div>

          <form onSubmit={handleEntry} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Visitor Name</label>
              <input
                type="text"
                value={visitorName}
                onChange={(e) => setVisitorName(e.target.value)}
                className="input-field"
                placeholder="Enter visitor's name"
                required
              />
            </div>
            <div className="flex gap-3">
              <button type="button" onClick={reset} className="btn-secondary flex-1">Cancel</button>
              <button type="submit" disabled={loading} className="btn-success flex-1">
                {loading ? 'Recording...' : 'Record Entry'}
              </button>
            </div>
          </form>
        </div>
      )}

      {step === 'done' && (
        <div className="card text-center">
          <div className="w-20 h-20 mx-auto bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mb-4">
            <HiOutlineCheckCircle className="w-10 h-10 text-emerald-600" />
          </div>
          <h3 className="text-xl font-bold mb-2">Entry Recorded Successfully</h3>
          <p className="text-gray-500 dark:text-gray-400 mb-6">Visitor "{visitorName}" has been logged.</p>
          <button onClick={reset} className="btn-primary">Verify Another Code</button>
        </div>
      )}
    </div>
  );
};

export default VerifyCodePage;
